### ISSUE TITLE
SMS verification code

### ISSUE THREAD

**Issue by ghost** [LibreSignal/LibreSignal#15]
Might the changed package id (or even the signing key) cause trouble with the SMS verification/registration? Do you know what is sent out to receive the verification code?

It still works right now, but you should look into this issue rather sonner than later, just to be on the safe side.

**Comment by mimi89999** [comment]
Yes,
GET /v1/accounts/{transport}/code/{number}
transport is the string sms or voice.
(https://github.com/WhisperSystems/TextSecure-Server/wiki/API-Protocol)
