### ISSUE TITLE
update to 3.14 release

### ISSUE THREAD

**Issue by pravi** [LibreSignal/LibreSignal#16]
Bug fixes can help improve performance and increase reliability.

**Comment by mimi89999** [comment]
It's already updated to 3.14.2. You can check the manifest file...

**Comment by pravi** [comment]
But fdroid is still not showing an update even after manual refresh.

**Comment by mimi89999** [comment]
Because @xmikos hasn't updated his repo.

**Comment by pravi** [comment]
Ok. I thought this will become the central repo for LibreSignal.

**Comment by pravi** [comment]
@xmikos can you update the repo? Also it would be good to sync with updates in this repo.

**Comment by mimi89999** [comment]
His F-Droid repo...

**Comment by xmikos** [comment]
I will switch eutopia.cz repository to your fork today. Builds will be available soon.

**Comment by mimi89999** [comment]
Did you see my PR?

**Comment by mimi89999** [comment]
@pravi Updated.

**Comment by xmikos** [comment]
Yes, I have already merged it, but it has needed some changes to be able to build (and also to be backward compatible with version naming scheme previously used in my repo). But now it is finally updated! ;-)
