### ISSUE TITLE
Signal-Desktop with Libresignal

### ISSUE THREAD

**Issue by Ray-Ven** [LibreSignal/LibreSignal#18]
Is it possible to use LibreSignal with Signal-Desktop? Will there be LibreSignal-Desktop if not? Will you remove option to add devices in Libresignal if both won't happen?

Thank you

**Comment by benediktg** [comment]
With the Libresignal build from fdroid.eutopia.cz it works as far as I can say –  I have two Chrome Web Apps connected to it.

**Comment by Ray-Ven** [comment]
hmm, I installed it via fdroid (experimental branch of libresignal). Maybe it's phone related (Jolla with sailfish)

**Comment by benediktg** [comment]
Did you already "register" for the beta of the Chrome Web App?

**Comment by Ray-Ven** [comment]
I did some time ago but didn't get any response. I thought, I'd just get the beta app as chrome extension then. After I got no response, I just cloned their git repository and activated the folder in chromium.
So the extension only works if they somehow "activate" my account?
(OT: I'm beginning to hate signal more and more... Closed Servers, no official websocket support, and some strange registration processes to an chrome extension?!?)

**Comment by JavaJens** [comment]
Are you using the right server? https://github.com/WhisperSystems/Signal-Desktop/blob/d84400777fa9ca3728411c787bb6f9ab50529a40/js/background.js

**Comment by Ray-Ven** [comment]
@JavaJens, are you reffering to this (from CONTRIBUTING.md):

> **Important!** The staging server uses a [self-signed ssl
> certificate](https://github.com/WhisperSystems/Signal-Browser/issues/110).
> By default, your browser will reject this certificate as insecure. Therefore,
> in order to register or send and receive messages of any kind, you must first
> visit https://textsecure-service-staging.whispersystems.org/ in a new tab and
> click through the warnings to allow the certificate. If done successfully,
> you should get a 404 from the server. If at any time in the future you notice
> a console error about an "INSECURE RESPONSE" or "Handshake was canceled",
> repeat this step.
> Or do I have to point to textsecure-service-staging.whispersystems.org somewhere else?

**Comment by JavaJens** [comment]
You didn't specify what issue you were experiencing, so I was just wild guessing.
There are two servers used: one for production, the other for testing.
You have to set both applications (desktop+phone) to point to the same server.

I'd guess you have to remove the `-staging` to point to the same server as your phone.

**Comment by mimi89999** [comment]
https://github.com/WhisperSystems/Signal-Desktop/search?utf8=%E2%9C%93&q=staging&type=Code

**Comment by Ray-Ven** [comment]
Ah ok, that did the trick. Thank you very much

If someone else runs into this. This is a little HowTo:
- Start Chrome/Chromium
- Activate Developermode in Chromium (Settings --> Extensions)
- install git, git clone signal-desktop repo
- Add extracted Extension into Chromium from folder containing signal-desktop
- change https://textsecure-service-staging.whispersystems.org/ to https://textsecure-service.whispersystems.org/ in signal-desktop/js/background.js
- visit https://textsecure-service-staging.whispersystems.org/ with chromium and accept ssl connection
- start signal-desktop in chromium
- use signal-desktop
