### ISSUE TITLE
Can`t register to signal - network error

### ISSUE THREAD

**Issue by zahnpasta12** [LibreSignal/LibreSignal#19]
Installed xmico`s apk on a tablet without umts/3g. After trying to register, reciving the 6-digit code via sms to a mobile-phone and entering the 6-digit in the given field, registration will fail with a "network error" -message.

**Comment by mimi89999** [comment]
The code received by SMS is only valid for a short period of time. Could you please try once again?

**Comment by JavaJens** [comment]
I think the code you can enter in the 6-digit field has to be the one you received through the call.
So you have to request the code twice, one via sms that you ignore and then another one which you can enter.

**Comment by zahnpasta12** [comment]
Thank you JavaJens. That solved the issue. Didn`t read carefully enough. The sim in my phone was not voice-enabled (umts-only) and i assumed that the sms-6-digit, which is valid for 20 min, is the same as the one given by the voice-recall. But it was not. Changed the sim with a voice-enabled one  and entered that digit and it worked. Thank you so much! Not only for the hint, but for your work in general, too.
