### ISSUE TITLE
clarify the state and goals of this project

### ISSUE THREAD

**Issue by anarcat** [LibreSignal/LibreSignal#20]
right now, people are confused about the goals of libresignal: is it aimed at replacing Signal's functionalities one to one? #10 has been marked as "wontfix" - so I guess that voice calls are out of the question for now, which brings the question of what libresignal actually brings on top of tools like conversations or kontalk.

is the goal right now to merge into one of those other projects and stop trying to replicate signal?

or is there a will to get into the official f-droid repo or at least support libresignal in the long term?

an example of the issue at hand could be mentionned here: https://pod.disroot.org/p/215927 in that cryptoparty, users are advised to activate old F-droid and Guardian project repositories without clearly explaining the impact this has on their systems... old apps may be installed without the user being conscious that those apps are not supported at all anymore.

it is not good practice to encourage people to install unsupported apps... it is especially confusing that libresignal shows up on the main f-droid frontpage, yet is not actually available there:

https://f-droid.org/repository/browse/?fdid=org.libresignal

could this situation be clarified? is there such a thing as libresignal, or is this just an experiment?

**Comment by mimi89999** [comment]
LibreSignal is now in the F-Droid archive repo for a testing period. Once the testing period will be over, it will be moved to the official F-Droid repo.

**Comment by mimi89999** [comment]
The goal of this project is to remove all non-free parts of Signal like GCM or location/map and maybe replace them by free alternatives.
Also, if a PR or a feature is not accepted by OWS, I might consider merging or adding it here if I consider it usefull.

**Comment by mimi89999** [comment]
As for #10 I think we should try to convince OWS to open source RedPhone server before thinking of replacing it by something eles.

**Comment by anarcat** [comment]
thanks for the response! maybe those goals could be made explicit in the readme and the package description?

**Comment by anarcat** [comment]
and well, regarding #10 - they explicitly said "not supported" there... not sure how that's gonna work.

**Comment by mimi89999** [comment]
Please see the [FAQ](https://github.com/LibreSignal/LibreSignal/wiki/FAQ), that I just wrote.
