### ISSUE TITLE
Replace libnative-utils.so

### ISSUE THREAD

**Issue by mimi89999** [LibreSignal/LibreSignal#21]
Replace libnative-utils.so

fdroid scanner reports an error (`ERROR: Found shared library at libs/{arch}/libnative-utils.so`). We should replace it by the source. The problem is that I can't find the source. @LibreSignal @xmikos

**Comment by xmikos** [comment]
Sources are in `jni` directory, look at `jni/Android.mk` makefile. libnative-utils.so source code is specificaly at `$(JNI_DIR)/utils/org_thoughtcrime_securesms_util_FileUtils.cpp`

**Comment by mimi89999** [comment]
Stupid issue... I just woke up and I'm not to bright yet...

**Comment by xmikos** [comment]
IMHO problem is that you don't have `buildjni=jni` line in F-Droid build file for LibreSignal. This is why native libraries aren't rebuild from sources (which is also why `libredphone-audio.so` is included in my build but not in F-Droid build).

**Comment by mimi89999** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/1229/diffs#note_3881911

**Comment by mimi89999** [comment]
I think it should be `buildjni=jni`, but @mvdan wrote https://gitlab.com/fdroid/fdroiddata/merge_requests/1229#note_3881911 and then the line disappeared in one of my commits. :/

**Comment by mvdan** [comment]
`buildjni=jni` is redundant. `yes` builds what's in `jni/`.

**Comment by xmikos** [comment]
@mvdan Are you sure about it? Last time I have tried `buildjni=yes` in LibreSignal build, it failed. Only `buildjni=jni` worked for me. I will try it again next time...

**Comment by JavaJens** [comment]
@xmikos Should work `buildjni=[yes|no|<dir list>]` according to https://f-droid.org/manual/html_node/Build.html

Edit: Nevermind, you need to specify the directory if it is not `.`

**Comment by mimi89999** [comment]
@mvdan Building LibreSignal with `buildjni=yes` still fails.

**Comment by JavaJens** [comment]
@mimi89999 Check the link i posted. I'd say, you need to specify `buildjni=jni`
