### ISSUE TITLE
How to migrate?

### ISSUE THREAD

**Issue by sim6** [LibreSignal/LibreSignal#22]
Firstly thanks for your work.

I migrated my Signal installation (in fact LibreSignal from fdroid.eutopia.cz repository) to LibreSignal with the following steps:

```
adb root
adb shell
ls -ld /data/data/org.libresignal
# look the user and group
mv /data/data/org.thoughtcrime.securesms/!(lib) /data/data/org.libresignal
chown -R u0_a65:u0_a65 /data/data/org.libresignal/!(lib)
mv /data/data/org.libresignal/shared_prefs/org.thoughtcrime.securesms_preferences.xml /data/data/org.libresignal/shared_prefs/org.libresignal_preferences.xml
sqlite3 /data/data/org.libresignal/databases/messages.db "UPDATE part SET _data = replace(_data, '/data/data/org.thoughtcrime.securesms/', '/data/data/org.libresignal/'), thumbnail = replace(thumbnail, '/data/data/org.thoughtcrime.securesms/', '/data/data/org.libresignal/') WHERE _data LIKE '/data/data/org.thoughtcrime.securesms/%'"
```

Is it enough? What about Signal android account?

**Comment by mimi89999** [comment]
I think it is enough.

**Comment by pejakm** [comment]
Don't forget to reset secure sessions with your contacts.

**Comment by sim6** [comment]
Thanks @mimi89999 
@pejakm My conversations works without reseting the secure session.

**Comment by sim6** [comment]
I am going to close the issue, but please add comments if you want.

**Comment by ingerling** [comment]
Is it be possible to do the migration with oandbackup?
I tried it, but without success...

**Comment by mimi89999** [comment]
1. Backup with oand
2. Go to oandbackup folder
3. Rename org.thoughtcrime.securesms folder to org.libresignal
4. Rename the .log file and the .zip in this folder
5. Replace all org.thoughtcrime.securesms strings with org.libresignal in the .log file
6. Open the .zip and rename org.thoughtcrime.securesms_preferences.xml to org.libresignal_preferences.xml in shared_prefs
7. Restore with oand

**Comment by ingerling** [comment]
Thank you, worked like a charm!

**Comment by mimi89999** [comment]
Maybe I will add this to README later.

**Comment by mimi89999** [comment]
But my instructions didn't include making chsnges to the database.
