### ISSUE TITLE
App pulled from F-Droid?

### ISSUE THREAD

**Issue by tuxayo** [LibreSignal/LibreSignal#24]
Can't find by research nor by the link in the readme.

https://f-droid.org/repository/browse/?fdid=org.libresignal

**Comment by r00tler** [comment]
The app is in the f-droid archive repo for testing and not yet listed on the website. You can install it by enabling the repo in f-droid.

**Comment by mimi89999** [comment]
If you enable the archive repo in F-Droid and open this link with F-Droid, you will find the app.

**Comment by tuxayo** [comment]
> The app is in the f-droid archive repo for testing and not yet listed on the website.

Ok, I understand.
I had the archive repo enabled, that's how I found about LibreSignal. 

Thanks.
