### ISSUE TITLE
Remove Google Repository dependency

### ISSUE THREAD

**Issue by codedust** [LibreSignal/LibreSignal#26]
Google Repository is a proprietary library that we don't want to require to build the app.

EDIT: Upps. Android Support Repository seems to be Apache licensed.

**Comment by mimi89999** [comment]
:smile:

**Comment by codedust** [comment]
I think you got me wrong: Android Support is open source, but Google Repository is still something we don't want.

**Comment by mimi89999** [comment]
I looked at the date...

**Comment by codedust** [comment]
:)

**Comment by mimi89999** [comment]
@codedust Could you please quote the code, that you are talking about? I don't understand what you mean by "Google Repository"...

**Comment by codedust** [comment]
`BUILDING.md` states that you have to install it in order to compile the app.

```
Ensure that the following packages are installed from the Android SDK manager:
    Android SDK Build Tools
    SDK Platform (API level 22)
    Android Support Repository
    Google Repository <---
```

**Comment by mimi89999** [comment]
It isn't needed. I forgot to remove it from BUILDING...

**Comment by codedust** [comment]
:+1:
