### ISSUE TITLE
migrate Signal to LibreSignal

### ISSUE THREAD

**Issue by Diapolo** [LibreSignal/LibreSignal#31]
Is there an easy way to be able to keep all conversations, groups and so on, while moving to LibreSignal?

**Comment by mimi89999** [comment]
Yes. Oandbackup from F-Droid. You backup Signal data, uninstall the app, install LibreSignal and restore the backup

**Comment by mimi89999** [comment]
It also depends from where you install LibreSignal.

**Comment by Diapolo** [comment]
F-Droid Archive was my choice?

Oandbackup requires BusyBox, which my ROM seems to not have (CM13) :-/...

**Comment by mimi89999** [comment]
Look at #22

**Comment by mimi89999** [comment]
I should really add this somewhere (maybe the README?)

**Comment by mimi89999** [comment]
@Diapolo To fix Oandbackup you need to go to settings --> busybox and enter:
/system/bin/toybox
