### ISSUE TITLE
Add LibreSignal FAQ

### ISSUE THREAD

**Issue by mimi89999** [LibreSignal/LibreSignal#32]

**Comment by mimi89999** [comment]
(As a wiki page)

**Comment by mimi89999** [comment]
#28 #20 #31 #26 (?) #25 #24 #22 #19 (?) #18 (?) #17

**Comment by zahnpasta12** [comment]
I`m willing to help but how can I help you? 
(issue #19 or in generell )

**Comment by mimi89999** [comment]
https://github.com/LibreSignal/LibreSignal/wiki/FAQ
