### ISSUE TITLE
Varying max file size for attachements over signal-server?

### ISSUE THREAD

**Issue by zahnpasta12** [LibreSignal/LibreSignal#33]
I received a 3Mb videofile from a signal-user, but sending a 2.5 Mb file gave me an error "file is too large". On http://www.pcmag.com/article2/0,2817,2494534,00.asp the author says "During testing, when sending a video, I received an error saying that I'd exceeded the service's size limitation. It did not say what the limitation is. Your mileage may vary."

I couldn't find any other informations about this and how this is handled. Any further informations?

**Comment by mimi89999** [comment]
LibreSignal is using OWS servers. I think, that you should ask them about this.

**Comment by mimi89999** [comment]
https://github.com/WhisperSystems/Signal-Android/issues/700 https://github.com/WhisperSystems/Signal-Android/issues/2780

**Comment by zahnpasta12** [comment]
It is working now as it should. I can send  received files from Signal users to other Signal and LibreSignal users. Maybe it was a "server-hickup".
