### ISSUE TITLE
Application not found on F-Droid

### ISSUE THREAD

**Issue by Nordlenning** [LibreSignal/LibreSignal#34]
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

Due to problems with compiling APK in Android Studio 2.0 I tried to get it from F-Droid

Application not found.
### Steps to reproduce

Push F-Droid button to get the APK on F-Droid

**Actual result:** Application not found
**Expected result:** Application found & available for Download
### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by mimi89999** [comment]
https://github.com/LibreSignal/LibreSignal/wiki/FAQ
https://github.com/LibreSignal/LibreSignal/issues/24

**Comment by mimi89999** [comment]
@Nordlenning What was the problem with Android Studio?

**Comment by Nordlenning** [comment]
Hi

I don't know yet, just upgraded to 2.0 & having some issues with Gradle
build. I like the new Android Studio, looks nice so far.

Hopefully I will get it up & running smooth soon.

Found Signal Installed & running just fine.. Thanks.

**Comment by Nordlenning** [comment]
I'm having a issue with this, is there a quick fix :)

> Error:(13, 1) A problem occurred evaluating root project 'Libresignal'.
> Failed to apply plugin [id 'com.android.application']
> Gradle version 2.10 is required. Current version is 2.5. If using the gradle wrapper, try editing the distributionUrl in /root/Android/Libresignal/gradle/wrapper/gradle-wrapper.properties to gradle-2.10-all.zip

02:05:05 Gradle sync started
02:07:08 Executing tasks: [:]
02:07:11 Gradle sync completed
02:07:52 Gradle build finished with 1 error(s) in 44s 210ms
02:07:52 Gradle sync started
02:08:24 Gradle sync failed: No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
 Consult IDE log for more details (Help | Show Log)
02:13:59 Executing tasks: [assemble]
02:13:59 Gradle build finished with 1 error(s) in 697ms
02:13:59 Build APK: Errors while building APK. You can find the errors in the 'Messages' view.
