### ISSUE TITLE
connection problems (edited)

### ISSUE THREAD

**Issue by v3nd3tta1337** [LibreSignal/LibreSignal#39]
I have:
### Bug description

Edited: Some days messages don't seem to work
### Steps to reproduce
- send a message
- only one checkmark
### Device info

**Device:** Samsung Galaxy S I9000
**Android version:** CM11/ 4.4.4
**Signal version:** LibreSignal (eutopia) 3.15.2-websocket
### Details (edited)

While until 19.05.16 12:00 CEST all seemed to work, since then i have not gotten any messages from stock Signal users, but i have seen on a friends phone that day that she wrote me at 13:00 and i have never received the message, neither did messaging her work anymore.

(edited because i previously thought mox did pull the plug)

**Comment by mimi89999** [comment]
Could you send me the log? I can't test if it works because I asked all of my Signal/LibreSignal contacts to move to Conversations.

**Comment by v3nd3tta1337** [comment]
The problem seems to have been a temporarily issue, but the one certain message i did see yesterday on her phone defenitely to me still did not appear.
Also, both, me and the contact have to be in the app for the messages to send.
Furthermore LS crashes every now and then - maybe because the storage space for the convos gets too much when the "autotrim" is disabled - but this might be an issue with my old I9000.
And about logs... ugh this would be my first one, can't do one atm.

**Comment by mimi89999** [comment]
You may need to turn off battery optimization for LibreSignal.
As for taking the log, you can do that from LibreSignal setting.

**Comment by v3nd3tta1337** [comment]
To not alarm anyone else i edited the title and description. 

Battery optimization is turned off,
all day long i did not leave my home wifi, the only thing interfering with wifi
is the Wi-Fi Privacy Guard i have installed, but it should not have done anything.
All other messaging apps worked flawlessly.

**Comment by mimi89999** [comment]
Could somebody PM me his phone number, so I could test this? I asked all of my contacts to move to Conversations and I won't ask them to come back to LibreSignal...

**Comment by mimi89999** [comment]
I can't reproduce this issue.

**Comment by MaxMatti** [comment]
@mimi89999 You have more mail and also I was able to send and receive messages.
Is this a location-sensitive problem?
Edit: the call crashed the app, but that's as expected on BlackBerry.
[Link](http://imgur.com/BzNbfvJ)

**Comment by mimi89999** [comment]
@MaxMatti I sent you a message in LibreSignal.

**Comment by mimi89999** [comment]
@v3nd3tta1337 I couldn't reproduce this issue. Maybe it is related to your ROM or to your network... I won't do further debugging because of #37 , but if you send me your log, I will look at it.

**Comment by mimi89999** [comment]
Could you please recheck that?
