### ISSUE TITLE
Too high battery drain

### ISSUE THREAD

**Issue by gsantner** [LibreSignal/LibreSignal#40]
I have:
- [x ] searched open and closed issues for duplicates
- [x ] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

---
### Bug description

LibreSignal consumes too much power. I send about 5 messages a week currently, and it constantly drains **20-25%** of my phones battery, doesn't matter if in use or not. I know theres the websocket in the background which demands, but the current state makes it hard to keep it on the device.
Some time ago there were battery issues at TextSecure, but I could not find any recent Signal issues about this.
### Steps to reproduce
- Launch LibreSignal once via App Drawer
- or at boot time

**Actual result:** ~20% battery usage
**Expected result:** 3-6% batttery usage
### Screenshots

![photo_2016-05-22_10-47-49](https://cloud.githubusercontent.com/assets/6735650/15453180/030aae12-200c-11e6-9e66-a3c0480dd442.jpg)
![photo_2016-05-22_10-47-53](https://cloud.githubusercontent.com/assets/6735650/15453184/21c56798-200c-11e6-98f5-0236fe8393fa.jpg)
### Device info

**Device:** LG Nexus 5
**Android version:** 6.0.1
**Signal version:** 3.15.2-websocket

**Comment by mimi89999** [comment]
'WONTFIX' because of #37

**Comment by mimi89999** [comment]
As for battery usage, it is acceptable when used over Wi-Fi, but there is a battery drain when used over mobile data.

**Comment by gsantner** [comment]
Thanks for your reply, I spent much time reading that discussion. I am feeling really bad about the project's status. I just didn't see that issue, please link to it in README.md, so other users get to know the current status aswell. ;)

Kind regards, Gregor
