### ISSUE TITLE
Calling in LibreSignal

### ISSUE THREAD

**Issue by herbsmn** [LibreSignal/LibreSignal#53]
I know that LibreSignal calls used to not work because it depended on nonfree software. Signal then moved to WebRTC. Calls still don't work for me in LibreSignal though. The app crashes when I try. Does it work for anyone else? I use a Replicant ROM on samsung galaxy s3.

**Comment by mimi89999** [comment]
LibreSignal WebSocket (from Eutopia experimental repp) is not maintained for a year now. If you are using LS from Eutopia main repo, those are xmikos builds of Signal and you should report that issue in his repo.
