### ISSUE TITLE
"focus on another ..."

### ISSUE THREAD

**Issue by goyalyashpal** [LibreSignal/LibreSignal#57]
> Stop LibreSignal and focus on another secure messaging app.

_Originally posted by @mimi89999 in https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-217449686_

hi, did u switch to contributing to other messaging app? which one, if yes?

dupli search: https://github.com/LibreSignal/LibreSignal/issues?q=is:issue+focus+on+another+secured+messaging  
coming via: [fdroid archive](https://duckduckgo.com/?q=fdroid+archive&t=vivaldi&ia=web) > [known repo](https://f-droid.org/wiki/page/Known_Repositories) > Eutopia

**Comment by mimi89999** [comment]
> hi, did u switch to contributing to other messaging app? which one, if yes?

XMPP clients like Conversations

**Comment by goyalyashpal** [comment]
ohkayyy. 👍 

`eu.siacs.conversations`
<-- https://conversations.im
<-- [Conversations](https://duckduckgo.com/?q=Conversations&t=vivaldi&page=1&ia=web)

**Comment by sim6** [comment]
What about https://matrix.org ones?
