### ISSUE TITLE
Overtake LibreSignal Twitter Account

### ISSUE THREAD

**Issue by SecUpwN** [LibreSignal/LibreSignal#7]
I am currently editing your `README` and wondered if you'll be overtaking the official [LibreSignal Twitter Account](https://twitter.com/libresignal) from @xmikos as well. If so, I'd like to add it to the `README`. What do you think, @mimi89999?

**Comment by mimi89999** [comment]
No, I won't.

**Comment by SecUpwN** [comment]
>No, I won't.

Ok. Shall I still add it or leave it out for now?

**Comment by SecUpwN** [comment]
> No, I won't.

Fair. Should @xmikos decide to hand over the Twitter account, we might add it to our `README` later on.
