### ISSUE TITLE
Add project description

### ISSUE THREAD

**Issue by SecUpwN** [LibreSignal/LibreSignal#9]
Hey @mimi89999, your wonderful fork does not yet contain a description, it just tells `No description or website provided.` If I were in your organization, I would add it myself, but since I am not, how about:

`LibreSignal • The truly private messenger for Android. Without Google!`

**Comment by mimi89999** [comment]
I invited you...

**Comment by SecUpwN** [comment]
> I invited you...

Thanks, I already accepted. Seems I cannot edit the project description though. Maybe because I still lack `COLLABORATOR` status or something. But you may as well edit it yourself if you don't want to grant it.

**Comment by mimi89999** [comment]
I think now you should have write access to the repo.

**Comment by mimi89999** [comment]
What about:
LibreSignal • The truly private messenger for Android. It's Google-Free!
or
LibreSignal • The truly private and Google-Free messenger for Android.
?

**Comment by SecUpwN** [comment]
> I think now you should have write access to the repo.

No, I don't. I guess you'll have to add me as `COLLABORATOR` in tab `Settings` as well. Regarding the project description: Would you rather stay closer to the original one from `Signal`? They say: `A private messenger for Android.` Which one of the above proposals do you like best? We need a third voice.

**Comment by mimi89999** [comment]
Or maybe:
A/The free-as-in-freedom truly private messenger for Android.

**Comment by SecUpwN** [comment]
> The free-as-in-freedom truly private messenger for Android.

I'm honest when I say that it does not sounds very professional. ;-)
I've edited the description to test how it looks. How do you like it now?

**Comment by mimi89999** [comment]
I like it a lot.

**Comment by SecUpwN** [comment]
> I like it a lot.

Perfect! Also edited our `LibreSignal` organization a bit so that it looks more professional. Let's rock! :guitar:
